#
# This is the file your server opens to find the main class
# of your plugin and its information. We automatically replace
# many variables here from your pom.xml file.
#
# See https://www.spigotmc.org/wiki/plugin-yml/ for more
# information .
#
# NB: Please do not register commands here, these are done
# directly in our plugin using Foundation :)
#
name: currencyplugin
version: 1.0.0
main: io.dubois.plugin.CurrencyPlugin
author: jdoobi3
api-version: 1.13